# Pull base image
FROM nginx


# Dockerfile Maintainer
MAINTAINER HimanshuMahajan "himanshu"

# nginx config
COPY index.html /usr/share/nginx/html


# Expose HTTP
EXPOSE 80

# Start nginx
CMD ["/usr/sbin/nginx"]